//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.4918
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toodie {
	using System;
	
	
	/// <summary>
	///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągw itd.
	/// </summary>
	// Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
	// przez narzędzie, takie jak ResGen lub Visual Studio.
	// Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
	// z opcją /str lub ponownie utwrz projekt VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Localization_pl_PL {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Localization_pl_PL() {
		}
		
		/// <summary>
		/// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toodie.Localization.pl-PL", typeof(Localization_pl_PL).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Zastępuje właściwość CurrentUICulture bieżącego wątku dla wszystkich
		///   przypadkw przeszukiwania zasobw za pomocą tej klasy zasobw wymagającej zdefiniowania typu.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu O...
		/// </summary>
		internal static string about {
			get {
				return ResourceManager.GetString("about", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Aktualny projekt aktualny okres.
		/// </summary>
		internal static string ActProjActFocus {
			get {
				return ResourceManager.GetString("ActProjActFocus", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Aktualny projekt wszystkie okresy.
		/// </summary>
		internal static string ActProjAllFocus {
			get {
				return ResourceManager.GetString("ActProjAllFocus", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj.
		/// </summary>
		internal static string add {
			get {
				return ResourceManager.GetString("add", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj nowy wpis.
		/// </summary>
		internal static string addNewItem {
			get {
				return ResourceManager.GetString("addNewItem", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Moja nowa lista zadań.
		/// </summary>
		internal static string AllProjActFocus {
			get {
				return ResourceManager.GetString("AllProjActFocus", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Wszystkie.
		/// </summary>
		internal static string AllProjAllFocus {
			get {
				return ResourceManager.GetString("AllProjAllFocus", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień termin.
		/// </summary>
		internal static string changeFocus {
			get {
				return ResourceManager.GetString("changeFocus", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień projekt.
		/// </summary>
		internal static string changeProject {
			get {
				return ResourceManager.GetString("changeProject", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Stwórz kopię zapasową.
		/// </summary>
		internal static string changes {
			get {
				return ResourceManager.GetString("changes", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Sprawdź aktualizacje....
		/// </summary>
		internal static string checkForUpdates {
			get {
				return ResourceManager.GetString("checkForUpdates", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Szukam uaktualnień ....
		/// </summary>
		internal static string checking_for_updates {
			get {
				return ResourceManager.GetString("checking_for_updates", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Proces ukończony.
		/// </summary>
		internal static string completed {
			get {
				return ResourceManager.GetString("completed", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy jesteś pewien że chcesz usunąć projekt wraz z jego zadaniami ?.
		/// </summary>
		internal static string confirmation_delProject {
			get {
				return ResourceManager.GetString("confirmation_delProject", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd łączenia ze zdalnym serwerem..
		/// </summary>
		internal static string connectionError {
			get {
				return ResourceManager.GetString("connectionError", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Stwórz kopię zapasową.
		/// </summary>
		internal static string createbackup {
			get {
				return ResourceManager.GetString("createbackup", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Data.
		/// </summary>
		internal static string date {
			get {
				return ResourceManager.GetString("date", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Pobrać nową wersję ?.
		/// </summary>
		internal static string download {
			get {
				return ResourceManager.GetString("download", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd i eksport nie może zostać ukończony..
		/// </summary>
		internal static string error1 {
			get {
				return ResourceManager.GetString("error1", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyjdź.
		/// </summary>
		internal static string exit {
			get {
				return ResourceManager.GetString("exit", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Eksport.
		/// </summary>
		internal static string export {
			get {
				return ResourceManager.GetString("export", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Eksportuj i drukuj.
		/// </summary>
		internal static string exportAndPrint {
			get {
				return ResourceManager.GetString("exportAndPrint", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz format eksportu.
		/// </summary>
		internal static string exportFormat {
			get {
				return ResourceManager.GetString("exportFormat", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz zakres eksportu.
		/// </summary>
		internal static string exportRange {
			get {
				return ResourceManager.GetString("exportRange", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Eksportuj .
		/// </summary>
		internal static string exportToPDF {
			get {
				return ResourceManager.GetString("exportToPDF", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Plik.
		/// </summary>
		internal static string file {
			get {
				return ResourceManager.GetString("file", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Pliki.
		/// </summary>
		internal static string files {
			get {
				return ResourceManager.GetString("files", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Znajdź.
		/// </summary>
		internal static string find {
			get {
				return ResourceManager.GetString("find", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Aktualne.
		/// </summary>
		internal static string Focus_actual {
			get {
				return ResourceManager.GetString("Focus_actual", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu W przyszlośći.
		/// </summary>
		internal static string Focus_future {
			get {
				return ResourceManager.GetString("Focus_future", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Któregoś dnia.
		/// </summary>
		internal static string Focus_someday {
			get {
				return ResourceManager.GetString("Focus_someday", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Oczekiwane.
		/// </summary>
		internal static string Focus_tomorrow {
			get {
				return ResourceManager.GetString("Focus_tomorrow", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomoc.
		/// </summary>
		internal static string help {
			get {
				return ResourceManager.GetString("help", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Ukryj zakończone zadana.
		/// </summary>
		internal static string hideFinishedTasks {
			get {
				return ResourceManager.GetString("hideFinishedTasks", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Ukryj projekty.
		/// </summary>
		internal static string hideProjects {
			get {
				return ResourceManager.GetString("hideProjects", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Podświetlenie.
		/// </summary>
		internal static string highlight {
			get {
				return ResourceManager.GetString("highlight", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Importuj listę.
		/// </summary>
		internal static string importList {
			get {
				return ResourceManager.GetString("importList", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Zadania.
		/// </summary>
		internal static string items {
			get {
				return ResourceManager.GetString("items", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Język.
		/// </summary>
		internal static string language {
			get {
				return ResourceManager.GetString("language", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Moja nowa lista zadań.
		/// </summary>
		internal static string mynewtasklist {
			get {
				return ResourceManager.GetString("mynewtasklist", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Nowa lista zadań.
		/// </summary>
		internal static string newTaskList {
			get {
				return ResourceManager.GetString("newTaskList", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Nowa wersja jest dostępna..
		/// </summary>
		internal static string newVersion {
			get {
				return ResourceManager.GetString("newVersion", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono bazy danych.
		/// </summary>
		internal static string nodatabase {
			get {
				return ResourceManager.GetString("nodatabase", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Musisz włączyć listę projektów i wybrać aktualny projekt..
		/// </summary>
		internal static string noProjectSelected {
			get {
				return ResourceManager.GetString("noProjectSelected", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Otwórz.
		/// </summary>
		internal static string open {
			get {
				return ResourceManager.GetString("open", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Ostatnio otwierane.
		/// </summary>
		internal static string openRecent {
			get {
				return ResourceManager.GetString("openRecent", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Otwórz listę zadań.
		/// </summary>
		internal static string opentasklist {
			get {
				return ResourceManager.GetString("opentasklist", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Drukuj.
		/// </summary>
		internal static string print {
			get {
				return ResourceManager.GetString("print", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Ten projekt już istnieje.
		/// </summary>
		internal static string projectExists {
			get {
				return ResourceManager.GetString("projectExists", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Projekty.
		/// </summary>
		internal static string projects {
			get {
				return ResourceManager.GetString("projects", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń.
		/// </summary>
		internal static string remove {
			get {
				return ResourceManager.GetString("remove", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień nazwę.
		/// </summary>
		internal static string rename {
			get {
				return ResourceManager.GetString("rename", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń aktualny projekt.
		/// </summary>
		internal static string resetList {
			get {
				return ResourceManager.GetString("resetList", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Utwórz kopię zapasową.
		/// </summary>
		internal static string save {
			get {
				return ResourceManager.GetString("save", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz listę zadań ....
		/// </summary>
		internal static string saveTasks {
			get {
				return ResourceManager.GetString("saveTasks", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Szukaj.
		/// </summary>
		internal static string search {
			get {
				return ResourceManager.GetString("search", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Wprowadź tekst....
		/// </summary>
		internal static string search_phrase {
			get {
				return ResourceManager.GetString("search_phrase", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Szukanie nowej wersji ....
		/// </summary>
		internal static string searching_updates {
			get {
				return ResourceManager.GetString("searching_updates", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Pokaż statystyki.
		/// </summary>
		internal static string showStatistics {
			get {
				return ResourceManager.GetString("showStatistics", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu .
		/// </summary>
		internal static string String {
			get {
				return ResourceManager.GetString("String", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Synchronizuj.
		/// </summary>
		internal static string sync {
			get {
				return ResourceManager.GetString("sync", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Zadanie.
		/// </summary>
		internal static string task {
			get {
				return ResourceManager.GetString("task", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Ukryj notatki.
		/// </summary>
		internal static string taskInformation {
			get {
				return ResourceManager.GetString("taskInformation", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Lista zadań.
		/// </summary>
		internal static string taskList {
			get {
				return ResourceManager.GetString("taskList", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Baza danych Toodie.
		/// </summary>
		internal static string toodieDatabase {
			get {
				return ResourceManager.GetString("toodieDatabase", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Narzędzia.
		/// </summary>
		internal static string tools {
			get {
				return ResourceManager.GetString("tools", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Do PDF.
		/// </summary>
		internal static string toPDF {
			get {
				return ResourceManager.GetString("toPDF", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Widok.
		/// </summary>
		internal static string view {
			get {
				return ResourceManager.GetString("view", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu z dotFTP.
		/// </summary>
		internal static string withDotFTP {
			get {
				return ResourceManager.GetString("withDotFTP", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu z Twoim FTP.
		/// </summary>
		internal static string withYourFTP {
			get {
				return ResourceManager.GetString("withYourFTP", resourceCulture);
			}
		}
		
		/// <summary>
		/// Wyszukuje zlokalizowany ciąg podobny do ciągu Bez projektu.
		/// </summary>
		internal static string yard {
			get {
				return ResourceManager.GetString("yard", resourceCulture);
			}
		}
	}
}
